<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Sauron.Application.Abstraction\Sauron.Application.Abstraction.csproj" />
	  <ProjectReference Include="..\Sauron.Domain\Sauron.Domain.csproj" />
	</ItemGroup>

</Project>
