<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sauron.Abstraction\Sauron.Abstraction.csproj" />
    <ProjectReference Include="..\Sauron.Domain.EfCore\Sauron.Domain.EfCore.csproj" />
  </ItemGroup>

</Project>
