<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="dbup" />
		<PackageReference Include="dbup-postgresql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Scripts/**/*.sql" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Scripts\Post\Always\" />
	  <Folder Include="Scripts\Post\Once\" />
	  <Folder Include="Scripts\Pre\Always\" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Scripts\Pre\Once\Schemas\Schema.Pre.Once.sql">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Scripts\Pre\Once\Tables\Adventurer.Pre.Once.sql">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
