<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="dbup" />
		<PackageReference Include="dbup-postgresql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Scripts/**/*.sql" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Scripts\" />
	</ItemGroup>

</Project>
